### ISSUE TITLE
Serializing error when sending an empty string

### ISSUE THREAD

**Issue by Kaev** [Foereaper/CSMH#2]
Sending an empty string to the server results in the empty string getting kicked out of the argument table.
Example:

Client
`SendClientRequest(config.Prefix, 1, "a", "", "b")`

Server
`print(argTable[1], argTable[2], argTable[3])`

Result
`a b nil`

**Comment by Foereaper** [comment]
Should be fixed after 62c12162e1107df47031d0d3a02185909568a75b
